### ISSUE TITLE
Motor stalls in turning and bumps.

### ISSUE THREAD

**Issue by malekhammoud** [mhammoud-os/GreenGuardian-Automated-Weed-Detection-and-Elimination#12]
It can't turn or move over bumps, need to use larger motor or use more motors.

**Comment by mhammoud-os** [comment]
Here is a link to a heavy duty motor that I will use. 
[https://www.amazon.ca/uxcell-Double-Torque-Reduction-Gearbox/dp/B078VV6RF7](https://www.amazon.ca/uxcell-Double-Torque-Reduction-Gearbox/dp/B078VV6RF7)

**Comment by mhammoud-os** [comment]
Turning is good when using a small wheel at the front, however the bumbs in the ground cause the veichle to become off course. Will experement with useing two motors with the steering mechanism in the front.

**Comment by mhammoud-os** [comment]
Front wheel turn, two back motors.
